lib/pet_clinic_mx_web/router.ex
defmodule PetClinicMxWeb.Router do
  use PetClinicMxWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PetClinicMxWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PetClinicMxWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/pets/by_type/:type", PetController, :index_by_type

    get(
      "/health_experts/:id/schedule",
      HealthExpertController,
      :index_appointments
    )

    resources "/pets", PetController
    resources "/health_experts", HealthExpertController
    resources "/owners", OwnerController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PetClinicMxWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PetClinicMxWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/pet_clinic_mx_web/views/healt_expert_view.ex
defmodule PetClinicMxWeb.HealthExpertView do
  use PetClinicMxWeb, :view
end

lib/pet_clinic_mx_web/templates/healt_expert/edit.html.heex
<h1>Edit Healt Expert</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.health_expert_path(@conn, :update, @health_expert)) %>

<span><%= link "Back", to: Routes.health_expert__path(@conn, :index) %></span>

lib/pet_clinic_mx_web/templates/healt_expert/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :age %>
  <%= number_input f, :age %>
  <%= error_tag f, :age %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :specialities %>
  <%= text_input f, :specialities %>
  <%= error_tag f, :specialities %>

  <%= label f, :sex %>
  <%= text_input f, :sex %>
  <%= error_tag f, :sex %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/pet_clinic_mx_web/templates/healt_expert/index.html.heex
<h1>Listing Healt expert</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Specialities</th>
      <th>Sex</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for health_expert <- @health_experts do %>
    <tr>
      <td><%= health_expert.name %></td>
      <td><%= health_expert.age %></td>
      <td><%= health_expert.email %></td>
      <td><%= health_expert.specialities %></td>
      <td><%= health_expert.sex %></td>

      <td>
        <span><%= link "Show", to: Routes.health_expert_path(@conn, :show, health_expert) %></span>
        <span><%= link "Edit", to: Routes.health_expert_path(@conn, :edit, health_expert) %></span>
        <span><%= link "Delete", to: Routes.health_expert_path(@conn, :delete, health_expert), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Healt Expert", to: Routes.health_expert_path(@conn, :new) %></span>

lib/pet_clinic_mx_web/templates/healt_expert/new.html.heex
<h1>New Healt Expert</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.healt_expert_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.health_expert_path(@conn, :index) %></span>

lib/pet_clinic_mx_web/templates/healt_expert/show.html.heex
<ul>
    <li>
      <section class='flexBoxContainer'>
        <div class='leftFlexBox'>
          <div class="nosotros_card">
            <h3 class="nosotros_card_name"> <%= @health_expert.name %>, <%= @health_expert.age %> </h3>
              <img  class={"nosotros_profile"} width="500" height="350" src={"/images/veterinary_symbol.png"} />


              <div class="container">     
                <span class="nosotros_card_years_old"></span>
                  <ul class="nosotros_card_skills">
                    <li> <%= @health_expert.specialities %> </li>
                    <li> <%= @health_expert.sex %> </li>
                    <li> <%= @health_expert.email %> </li>
                  </ul>
                  <div class="nosotros_card_description">
                    <span><%= link "Edit", to: Routes.health_expert_path(@conn, :edit, @health_expert) %></span> |
                    <span><%= link "Back", to: Routes.health_expert_path(@conn, :index) %></span>
                  </div>  
                  <%# ---
                  <div class="nosotros_card_description">
                    una pequeña seccion de acerca de ustedes, es decir, un parrafo de algo acerca de ustedes
                  </div>  
                  --- %>
              </div>
          </div>
        </div>
        <%# --- <div class='rightFlexBox'></div> --- %>
      </section>
    </li>
</ul>